const userData = [
  {
    id: 1,
    name: "Mark Webber",
    profileImage: "avatar-mark-webber",
    notifType: "REACTION",
    notifMessage: "My first tournament today!",
    time: "1m ago",
    unread: true,
  },
  {
    id: 2,
    name: "Angela Gray",
    profileImage: "avatar-angela-gray",
    notifType: "FOLLOW",
    notifMessage: "",
    time: "5m ago",
    unread: true,
  },
  {
    id: 3,
    name: "Jacob Thompson",
    profileImage: "avatar-jacob-thompson",
    notifType: "GROUP",
    groupAction: "JOINED_GROUP",
    notifMessage: "Chess Club",
    time: "1 day ago",
    unread: true,
  },
  {
    id: 4,
    name: "Rizky Hasanuddin",
    profileImage: "avatar-rizky-hasanuddin",
    notifType: "PRIVATE_MESSAGE",
    notifMessage:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    time: "5 days ago",
    unread: false,
  },
  {
    id: 5,
    name: "Kimberly Smith",
    profileImage: "avatar-kimberly-smith",
    notifType: "PICTURE_COMMENT",
    picture: "image-chess",
    notifMessage: "image-chess.webp",
    time: "1 week ago",
    unread: false,
  },
  {
    id: 6,
    name: "Nathan Peterson",
    profileImage: "avatar-nathan-peterson",
    notifType: "REACTION",
    notifMessage: "5 end-game strategies to increase your win rate",
    time: "2 weeks ago",
    unread: false,
  },
  {
    id: 7,
    name: "Anna Kim",
    profileImage: "avatar-anna-kim",
    notifType: "GROUP",
    groupAction: "LEFT_GROUP",
    notifMessage: "Chess Club",
    time: "2 weeks ago",
    unread: false,
  },
];

export default userData;
